modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "${mod_issues_page}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
credits = "${mod_credits}"
description = "${mod_description}"
displayURL = "${mod_homepage}"
logoFile = "assets/sinocore/logo.png"
displayTest = "MATCH_VERSION"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${neoforge_minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

features = { javaVersion = "${neoforge_java_version_range}" }

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[mixins]]
config = "sinocore-common.mixins.json"

[[mixins]]
config = "sinocore-neoforge.mixins.json"