name: Build

on:
  workflow_call:
    inputs:
      mod-release:
        required: true
        type: boolean
        default: true
      upload-artifacts:
        required: false
        type: boolean
        default: true
  workflow_dispatch:
    inputs:
      mod-release:
        required: true
        type: boolean
        default: false
        description: Release mode
      upload-artifacts:
        required: true
        type: boolean
        default: true
        description: Upload build artifacts

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate gradlew
        uses: gradle/actions/wrapper-validation@v5

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        env:
          MOD_RELEASE: ${{ inputs.mod-release }}
          MOD_CI: true
          MOD_CI_BUILD_NUMBER: ${{ github.run_number }}
        run: |
          chmod +x ./gradlew
          ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: inputs.upload-artifacts
        with:
          name: 'build'
          path: |
            build/libs
            fabric/build/libs
            neoforge/build/libs
          retention-days: 7