name: Build check
on:
  push:
    paths:
      - src/**/*
      - neoforge/**/*
      - fabric/**/*
      - test/**/*
      - build.gradle
      - gradle.properties
      - settings.gradle
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      mod-release: false
      upload-artifacts: false
